-- CreateTable
CREATE TABLE `cdr` (
    `accountcode` VARCHAR(80) NULL,
    `src` VARCHAR(80) NULL,
    `dst` VARCHAR(80) NULL,
    `dcontext` VARCHAR(80) NULL,
    `clid` VARCHAR(80) NULL,
    `channel` VARCHAR(80) NULL,
    `dstchannel` VARCHAR(80) NULL,
    `lastapp` VARCHAR(80) NULL,
    `lastdata` VARCHAR(80) NULL,
    `start` DATETIME(0) NULL,
    `answer` DATETIME(0) NULL,
    `end` DATETIME(0) NULL,
    `duration` INTEGER NULL,
    `billsec` INTEGER NULL,
    `disposition` VARCHAR(45) NULL,
    `amaflags` VARCHAR(45) NULL,
    `userfield` VARCHAR(256) NULL,
    `uniqueid` VARCHAR(150) NULL,
    `linkedid` VARCHAR(150) NULL,
    `peeraccount` VARCHAR(80) NULL,
    `sequence` INTEGER NULL
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ps_aors` (
    `id` VARCHAR(255) NOT NULL,
    `contact` VARCHAR(255) NULL,
    `default_expiration` INTEGER NULL,
    `mailboxes` VARCHAR(80) NULL,
    `max_contacts` INTEGER NULL,
    `minimum_expiration` INTEGER NULL,
    `remove_existing` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `qualify_frequency` INTEGER NULL,
    `authenticate_qualify` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `maximum_expiration` INTEGER NULL,
    `outbound_proxy` VARCHAR(255) NULL,
    `support_path` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `qualify_timeout` FLOAT NULL,
    `voicemail_extension` VARCHAR(40) NULL,
    `remove_unavailable` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,

    UNIQUE INDEX `id`(`id`),
    INDEX `ps_aors_id`(`id`),
    INDEX `ps_aors_qualifyfreq_contact`(`qualify_frequency`, `contact`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ps_auths` (
    `id` VARCHAR(255) NOT NULL,
    `auth_type` ENUM('md5', 'userpass', 'google_oauth') NULL,
    `nonce_lifetime` INTEGER NULL,
    `md5_cred` VARCHAR(40) NULL,
    `password` VARCHAR(80) NULL,
    `realm` VARCHAR(255) NULL,
    `username` VARCHAR(40) NULL,
    `refresh_token` VARCHAR(255) NULL,
    `oauth_clientid` VARCHAR(255) NULL,
    `oauth_secret` VARCHAR(255) NULL,

    UNIQUE INDEX `id`(`id`),
    INDEX `ps_auths_id`(`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ps_contacts` (
    `id` VARCHAR(255) NOT NULL,
    `uri` VARCHAR(511) NULL,
    `expiration_time` BIGINT NULL,
    `qualify_frequency` INTEGER NULL,
    `outbound_proxy` VARCHAR(255) NULL,
    `path` TEXT NULL,
    `user_agent` VARCHAR(255) NULL,
    `qualify_timeout` FLOAT NULL,
    `reg_server` VARCHAR(255) NULL,
    `authenticate_qualify` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `via_addr` VARCHAR(40) NULL,
    `via_port` INTEGER NULL,
    `call_id` VARCHAR(255) NULL,
    `endpoint` VARCHAR(255) NULL,
    `prune_on_boot` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,

    UNIQUE INDEX `id`(`id`),
    INDEX `ps_contacts_id`(`id`),
    INDEX `ps_contacts_qualifyfreq_exp`(`qualify_frequency`, `expiration_time`),
    UNIQUE INDEX `ps_contacts_uq`(`id`, `reg_server`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ps_domain_aliases` (
    `id` VARCHAR(255) NOT NULL,
    `domain` VARCHAR(255) NULL,

    UNIQUE INDEX `id`(`id`),
    INDEX `ps_domain_aliases_id`(`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ps_endpoint_id_ips` (
    `id` VARCHAR(255) NOT NULL,
    `endpoint` VARCHAR(255) NULL,
    `match` VARCHAR(80) NULL,
    `match_header` VARCHAR(255) NULL,
    `match_request_uri` VARCHAR(255) NULL,
    `srv_lookups` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,

    UNIQUE INDEX `id`(`id`),
    INDEX `ps_endpoint_id_ips_id`(`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ps_endpoints` (
    `id` VARCHAR(255) NOT NULL,
    `transport` VARCHAR(40) NULL,
    `aors` VARCHAR(2048) NULL,
    `auth` VARCHAR(255) NULL,
    `context` VARCHAR(40) NULL,
    `disallow` VARCHAR(200) NULL,
    `allow` VARCHAR(200) NULL,
    `direct_media` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `connected_line_method` ENUM('invite', 'reinvite', 'update') NULL,
    `direct_media_method` ENUM('invite', 'reinvite', 'update') NULL,
    `direct_media_glare_mitigation` ENUM('none', 'outgoing', 'incoming') NULL,
    `disable_direct_media_on_nat` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `dtmf_mode` ENUM('rfc4733', 'inband', 'info', 'auto') NULL,
    `external_media_address` VARCHAR(40) NULL,
    `force_rport` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `ice_support` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `identify_by` VARCHAR(80) NULL,
    `mailboxes` VARCHAR(40) NULL,
    `moh_suggest` VARCHAR(40) NULL,
    `outbound_auth` VARCHAR(255) NULL,
    `outbound_proxy` VARCHAR(255) NULL,
    `rewrite_contact` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `rtp_ipv6` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `rtp_symmetric` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `send_diversion` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `send_pai` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `send_rpid` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `timers_min_se` INTEGER NULL,
    `timers` ENUM('forced', 'no', 'required', 'yes') NULL,
    `timers_sess_expires` INTEGER NULL,
    `callerid` VARCHAR(40) NULL,
    `callerid_privacy` ENUM('allowed_not_screened', 'allowed_passed_screened', 'allowed_failed_screened', 'allowed', 'prohib_not_screened', 'prohib_passed_screened', 'prohib_failed_screened', 'prohib', 'unavailable') NULL,
    `callerid_tag` VARCHAR(40) NULL,
    `100rel` ENUM('no', 'required', 'peer_supported', 'yes') NULL,
    `aggregate_mwi` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `trust_id_inbound` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `trust_id_outbound` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `use_ptime` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `use_avpf` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `media_encryption` ENUM('no', 'sdes', 'dtls') NULL,
    `inband_progress` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `call_group` VARCHAR(40) NULL,
    `pickup_group` VARCHAR(40) NULL,
    `named_call_group` VARCHAR(40) NULL,
    `named_pickup_group` VARCHAR(40) NULL,
    `device_state_busy_at` INTEGER NULL,
    `fax_detect` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `t38_udptl` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `t38_udptl_ec` ENUM('none', 'fec', 'redundancy') NULL,
    `t38_udptl_maxdatagram` INTEGER NULL,
    `t38_udptl_nat` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `t38_udptl_ipv6` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `tone_zone` VARCHAR(40) NULL,
    `language` VARCHAR(40) NULL,
    `one_touch_recording` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `record_on_feature` VARCHAR(40) NULL,
    `record_off_feature` VARCHAR(40) NULL,
    `rtp_engine` VARCHAR(40) NULL,
    `allow_transfer` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `allow_subscribe` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `sdp_owner` VARCHAR(40) NULL,
    `sdp_session` VARCHAR(40) NULL,
    `tos_audio` VARCHAR(10) NULL,
    `tos_video` VARCHAR(10) NULL,
    `cos_audio` INTEGER NULL,
    `cos_video` INTEGER NULL,
    `sub_min_expiry` INTEGER NULL,
    `from_domain` VARCHAR(40) NULL,
    `from_user` VARCHAR(40) NULL,
    `mwi_from_user` VARCHAR(40) NULL,
    `dtls_verify` VARCHAR(40) NULL,
    `dtls_rekey` VARCHAR(40) NULL,
    `dtls_cert_file` VARCHAR(200) NULL,
    `dtls_private_key` VARCHAR(200) NULL,
    `dtls_cipher` VARCHAR(200) NULL,
    `dtls_ca_file` VARCHAR(200) NULL,
    `dtls_ca_path` VARCHAR(200) NULL,
    `dtls_setup` ENUM('active', 'passive', 'actpass') NULL,
    `srtp_tag_32` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `media_address` VARCHAR(40) NULL,
    `redirect_method` ENUM('user', 'uri_core', 'uri_pjsip') NULL,
    `set_var` TEXT NULL,
    `message_context` VARCHAR(40) NULL,
    `force_avp` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `media_use_received_transport` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `accountcode` VARCHAR(80) NULL,
    `user_eq_phone` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `moh_passthrough` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `media_encryption_optimistic` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `rpid_immediate` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `g726_non_standard` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `rtp_keepalive` INTEGER NULL,
    `rtp_timeout` INTEGER NULL,
    `rtp_timeout_hold` INTEGER NULL,
    `bind_rtp_to_media_address` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `voicemail_extension` VARCHAR(40) NULL,
    `deny` VARCHAR(95) NULL,
    `permit` VARCHAR(95) NULL,
    `acl` VARCHAR(40) NULL,
    `contact_deny` VARCHAR(95) NULL,
    `contact_permit` VARCHAR(95) NULL,
    `contact_acl` VARCHAR(40) NULL,
    `subscribe_context` VARCHAR(40) NULL,
    `fax_detect_timeout` INTEGER NULL,
    `contact_user` VARCHAR(80) NULL,
    `preferred_codec_only` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `asymmetric_rtp_codec` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `rtcp_mux` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `allow_overlap` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `refer_blind_progress` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `notify_early_inuse_ringing` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `max_audio_streams` INTEGER NULL,
    `max_video_streams` INTEGER NULL,
    `webrtc` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `dtls_fingerprint` ENUM('SHA-1', 'SHA-256') NULL,
    `incoming_mwi_mailbox` VARCHAR(40) NULL,
    `bundle` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `dtls_auto_generate_cert` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `follow_early_media_fork` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `accept_multiple_sdp_answers` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `suppress_q850_reason_headers` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `mwi_subscribe_replaces_unsolicited` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `trust_connected_line` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `send_connected_line` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `ignore_183_without_sdp` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `codec_prefs_incoming_offer` VARCHAR(128) NULL,
    `codec_prefs_outgoing_offer` VARCHAR(128) NULL,
    `codec_prefs_incoming_answer` VARCHAR(128) NULL,
    `codec_prefs_outgoing_answer` VARCHAR(128) NULL,
    `stir_shaken` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `send_history_info` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `allow_unauthenticated_options` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `t38_bind_udptl_to_media_address` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `geoloc_incoming_call_profile` VARCHAR(80) NULL,
    `geoloc_outgoing_call_profile` VARCHAR(80) NULL,
    `incoming_call_offer_pref` ENUM('local', 'local_first', 'remote', 'remote_first') NULL,
    `outgoing_call_offer_pref` ENUM('local', 'local_merge', 'local_first', 'remote', 'remote_merge', 'remote_first') NULL,
    `stir_shaken_profile` VARCHAR(80) NULL,
    `security_negotiation` ENUM('no', 'mediasec') NULL,
    `security_mechanisms` VARCHAR(512) NULL,
    `send_aoc` ENUM('off', 'on', 'false', 'true', 'no', 'yes') NULL,
    `overlap_context` VARCHAR(80) NULL,
    `tenantid` VARCHAR(80) NULL,

    UNIQUE INDEX `id`(`id`),
    INDEX `ps_endpoints_id`(`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
